# Generated by Django 5.0.6 on 2024-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_order_latitude_alter_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zoom',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
