# Generated by Django 5.0.6 on 2024-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_from', models.CharField(max_length=50)),
                ('ship_to', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
