# Generated by Django 5.0.6 on 2024-06-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_quotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
