# Generated by Django 5.0.6 on 2024-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_quotes_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_position',
            field=models.CharField(default='North Atlantic Ocean', max_length=40),
            preserve_default=False,
        ),
    ]
