# Generated by Django 5.0.6 on 2024-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
