# Generated by Django 5.0.6 on 2024-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shipper_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
