# Generated by Django 5.0.6 on 2024-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_mailerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=7)),
            ],
        ),
    ]
