# Generated by Django 5.0.6 on 2024-10-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.receiver'),
            preserve_default=False,
        ),
    ]
