# Generated by Django 5.0.6 on 2024-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_order_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='Package arrived at our facility and is being processed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
