# Generated by Django 5.0.6 on 2024-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_order_comment_order_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='Carton'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='piece_type',
            field=models.CharField(default='Carton', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
