# Generated by Django 5.0.6 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_order_description_order_height_order_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color_r', models.CharField(max_length=3)),
                ('color_b', models.CharField(max_length=3)),
                ('color_g', models.CharField(max_length=3)),
            ],
        ),
    ]
