# Generated by Django 5.0.6 on 2025-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_state_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
